### ISSUE TITLE
about "find_unused_parameters=True " in training

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmhuman3d#110]
File "/root/anaconda3/envs/zxh/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 528, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):

THX!

**Comment by Gzzgz** [comment]
so as  hourglass. I fixed apis/trains.py like this:

if distributed:
        #find_unused_parameters = cfg.get('find_unused_parameters', False)
        find_unused_parameters = True
and it works. But hrnet still has this error. I got some params are used, but hourglass and hrnet are different.

**Comment by mingyuan-zhang** [comment]
So you have found out which parameters are not used in hrnet?

**Comment by Gzzgz** [comment]
Ok
