### ISSUE TITLE
question about spin

### ISSUE THREAD

**Issue by akk-123** [open-mmlab/mmhuman3d#112]
hi, @caizhongang  
I have a question about spin, according to the [code ](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/models/architectures/mesh_estimator.py#L360)，If the train dataset have gt about vertices, shape, beta... spin direct use the gt as target to compute loss, so if I understand correctly, the smplify module is useless when data have gt, the spin just equal a simple regress model? 
only when data have no gt , we can use the smplify to optimize beta, shape, so we can get a better beta, shape, vertices as pseudo  label to train network?

another question, spin need xx_fit.npy as initial optim param， how to calculate the fit.npy by ourself

**Comment by caizhongang** [comment]
Hi @akk-123 ,

> If the train dataset have gt about vertices, shape, beta... spin direct use the gt as target to compute loss, so if I understand correctly, the smplify module is useless when data have gt, the spin just equal a simple regress model?

That's right, we follow the [official code of SPIN](https://github.com/nkolot/SPIN) to implement SPIN in MMHuman3D. If a dataset has GT SMPL, the pseudo GT will be replaced (see [here](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/models/architectures/mesh_estimator.py#L360-L367) ). However, note that only H36M (MoShed) and a part of MPI-INF-3DHP provides SMPL parameters out of the six datasets.

> another question, spin need xx_fit.npy as initial optim param， how to calculate the fit.npy by ourself

We have obtained similar requests (#106 and [wishlist](https://github.com/open-mmlab/mmhuman3d/discussions/47#discussioncomment-2171798) ) recently. The team will schedule to add this feature as soon as possible, please stay tuned with our [roadmap](https://github.com/open-mmlab/mmhuman3d/discussions/48), and we welcome community contribution so if you can help us implement it please start a PR following our [guideline](https://github.com/open-mmlab/mmhuman3d/blob/main/.github/CONTRIBUTING.md)
