### ISSUE TITLE
why Intrinsic Matrix is 4 x 4

### ISSUE THREAD

**Issue by akk-123** [open-mmlab/mmhuman3d#114]
@caizhongang 
 why Intrinsic Matrix K defined as 
```python
K = [
        [fx,   0,   px,   0],
        [0,   fy,   py,   0],
        [0,    0,    0,   1],
        [0,    0,    1,   0],
    ]
```
rather than
```python
K = [
        [fx,   0,   px],
        [0,   fy,   py],
        [0,    0,    1]
    ]
```

**Comment by akk-123** [comment]
@caizhongang 
hybrik config  has no attribute 'inference_pipeline', run Inference will get error

**Comment by caizhongang** [comment]
> @caizhongang why Intrinsic Matrix K defined as
> 
> ```python
> K = [
>         [fx,   0,   px,   0],
>         [0,   fy,   py,   0],
>         [0,    0,    0,   1],
>         [0,    0,    1,   0],
>     ]
> ```
> 
> rather than
> 
> ```python
> K = [
>         [fx,   0,   px],
>         [0,   fy,   py],
>         [0,    0,    1]
>     ]
> ```

Hi @akk-123 , we adopt 4x4 Pytorch3D intrinsic convention, but also support 3x3 OpenCV intrinsic convention. @JasonBoy1 will provide more elaboration on this.

---

> @caizhongang
> hybrik config has no attribute 'inference_pipeline', run Inference will get error

Currently HybrIK inference is not supported as it requires an additional 3D keypoint estimation model that is not included in MMHuman3D yet. @ttxskk will elaborate more on this.

**Comment by ttxskk** [comment]
Hi @akk-123, HybrIK inference needs the root joint estimated by RootNet that is not included in MMHuman3D yet. More discussion can be found in #15.

**Comment by akk-123** [comment]
@caizhongang @ttxskk thanks
another question, what the difference between visualize_smpl_calibration, visualize_smpl_hmr and visualize_smpl_pose,
what's more, I run the code according the visualize_smpl.md
```python
import torch
from mmhuman3d.core.visualization import visualize_T_pose

visualize_T_pose(
    num_frames=10,
    model_type='smpl',
    model_path=xxx,
    output_path='smpl_tpose.mp4',
    orbit_speed=(1, 0.5),
    resolution=(512, 512))
```
will get error
```
TypeError: render_smpl() got an unexpected keyword argument 'model_path'
```

**Comment by akk-123** [comment]
@ttxskk one more question，can you tell me more detail about [conver_verts_to_cam_coord](https://github.com/open-mmlab/mmhuman3d/blob/20a1c620ce7be0b7811299b2e471999922a4fbba/mmhuman3d/utils/demo_utils.py#L261)

1. what dose these code mean?
```
Ks = np.linalg.inv(K0) @ K1 @ K0
```
2. if I understand correctly, world convert to image by K[R T]，world convert to camera by [R T]，don't need K, why in conver_verts_to_cam_coord use K to compute, rather than rotation

**Comment by akk-123** [comment]
what's more, I'm really confused about K, although you said adopt 4x4 PyTorch3D intrinsic convention, but I can't find related tutorial about it,  if K is 4x4, image coord is compute by K[R T], so the image coord is 4-dim, but a pixel coord is 3-dim(homogeneous)

**Comment by ttxskk** [comment]
1. If you want to visualize the SMPL mesh predicted by HMR, you need to render the mesh into the image shaped 224*224, and then you need to resize the rendered image to the original image shape. This process can be defined as:
```

 K1K0(RX+T) or K0Ks(RX+T), where Ks = K0_inv*K1*K0

``` 

2.  I think these [codes](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/mesh/rasterizer.py#L146-L156) might help you understand these 3D transformations.

I don't know if this explanation answers your question @akk-123.

**Comment by akk-123** [comment]
so, why  use 
```
K0Ks(RX+T), where Ks = K0_inv*K1*K0， 
```
rather than directly use 
```
K1K0(RX+T)
```

**Comment by ttxskk** [comment]
Hi @akk-123, if using `K1K0(RX+T)`, you should use `K0`, `R`, `T` to get the rendered image shaped 224*224 first and then resize the rendered image to the original image according to the detected bbox. If using `K0Ks(RX+T)`, you only need to use `Ks` to transform mesh and then use the camera intrinsic to get the result.
