### ISSUE TITLE
Missing verts in visualize_smpl_pose

### ISSUE THREAD

**Issue by yl-1993** [open-mmlab/mmhuman3d#119]
[visualize_smpl_pose](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/visualization/visualize_smpl.py#L1177) receives `verts` but do not pass it to `render_smpl`.

**Comment by Gzzgz** [comment]
![图片](https://user-images.githubusercontent.com/15968092/156333791-ea090f95-d80e-4ad1-9dea-80fff6aba9c6.png)

**Comment by JasonBoy1** [comment]
@ttxskk  please link your PR number here.

**Comment by ttxskk** [comment]
> @ttxskk please link your PR number here.

Resolved in #111
