### ISSUE TITLE
Can not render the `Inference Demo`

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmhuman3d#136]
Tried two pc with different cuda&python versions, build the env from zero, build pytorch3d(0.6.1) from src, when I run Inference Demo, the output video is same as the input video.

After added '--draw_bbox', the boxed detected can see.

I tried different `render_choice` , same results.

Trying to debug but may not spend a lot time on it.

**Comment by ykk648** [comment]
the frame rate is different, input video is 12 fps and output is 30 fps, may caused by ffmpeg, not connected with render I assume

**Comment by ykk648** [comment]
inference log:

<details>
<summary>Details</summary>

load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
load checkpoint from local path: data/checkpoints/resnet50_hmr_pw3d.pth
[                                                  ] 0/40, elapsed: 0s, ETA:
[                                  ] 1/40, 1.8 task/s, elapsed: 1s, ETA:    21s
[>                                 ] 2/40, 3.2 task/s, elapsed: 1s, ETA:    12s
[>>                                ] 3/40, 4.2 task/s, elapsed: 1s, ETA:     9s
[>>>                               ] 4/40, 5.1 task/s, elapsed: 1s, ETA:     7s
[>>>>                              ] 5/40, 5.8 task/s, elapsed: 1s, ETA:     6s
[>>>>>                             ] 6/40, 6.5 task/s, elapsed: 1s, ETA:     5s
[>>>>>                             ] 7/40, 7.0 task/s, elapsed: 1s, ETA:     5s
[>>>>>>                            ] 8/40, 7.5 task/s, elapsed: 1s, ETA:     4s
[>>>>>>>                           ] 9/40, 8.0 task/s, elapsed: 1s, ETA:     4s
[>>>>>>>>                         ] 10/40, 8.3 task/s, elapsed: 1s, ETA:     4s
[>>>>>>>>>                        ] 11/40, 8.7 task/s, elapsed: 1s, ETA:     3s
[>>>>>>>>>                        ] 12/40, 9.0 task/s, elapsed: 1s, ETA:     3s
[>>>>>>>>>>                       ] 13/40, 9.3 task/s, elapsed: 1s, ETA:     3s
[>>>>>>>>>>>                      ] 14/40, 9.5 task/s, elapsed: 1s, ETA:     3s
[>>>>>>>>>>>>                     ] 15/40, 9.8 task/s, elapsed: 2s, ETA:     3s
[>>>>>>>>>>>>                    ] 16/40, 10.0 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>                   ] 17/40, 10.2 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>                  ] 18/40, 10.3 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>                 ] 19/40, 10.5 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>>                ] 20/40, 10.7 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>>                ] 21/40, 10.8 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>>>               ] 22/40, 10.9 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>>>>              ] 23/40, 11.1 task/s, elapsed: 2s, ETA:     2s
[>>>>>>>>>>>>>>>>>>>             ] 24/40, 11.2 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>            ] 25/40, 11.3 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>            ] 26/40, 11.4 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>           ] 27/40, 11.5 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>          ] 28/40, 11.6 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>         ] 29/40, 11.7 task/s, elapsed: 2s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>>        ] 30/40, 11.8 task/s, elapsed: 3s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>>        ] 31/40, 11.8 task/s, elapsed: 3s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>>>       ] 32/40, 11.9 task/s, elapsed: 3s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>>>>      ] 33/40, 12.0 task/s, elapsed: 3s, ETA:     1s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>     ] 34/40, 12.0 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>    ] 35/40, 12.1 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>    ] 36/40, 12.2 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   ] 37/40, 12.2 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  ] 38/40, 12.3 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ] 39/40, 12.3 task/s, elapsed: 3s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 40/40, 12.4 task/s, elapsed: 3s, ETA:     0s
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Overwriting vis_results/single_person_demo.mp4.
make dir vis_results/single_person_demo.mp4_output_temp
Make dir vis_results/single_person_demo.mp4_output_temp
Overwriting vis_results/single_person_demo.mp4.
Running "ffmpeg -y -threads 4 -start_number 0 -r 30 -i vis_results/single_person_demo.mp4_output_temp/%06d.png -frames:v 40 -profile:v baseline -level 3.0 -c:v libx264 -pix_fmt yuv420p -an -v error -loglevel error vis_results/single_person_demo.mp4"

</details>

**Comment by ttxskk** [comment]
Hi @ykk648, please try PR #134.

**Comment by ykk648** [comment]
it works, thx
