### ISSUE TITLE
Built mmhuman3d from zero, here's problems I have encountered.

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmhuman3d#141]
I have no human3d training exp before , most are datasets preprocess problems.

1. Inference demo render fail. solved by #136 
2. MPII official dataset missing `train.h5`, see #135 
3. MPI-INF-3DHP & Human3.6m needs extract frame first, I add `extract_img=True` in `convert_datasets.py`, it costs about 16 & 6 hours with low cpu consumation on one hard disk, no one had told me that :( 
4. According [human36m-mosh](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/preprocess_dataset.md#human36m-mosh), the file structure is `/datasets/h36m_mosh`, but the h36m_spin convertor acturally needs `/datasets/h36m_extras/mosh_data`
5. Where is h36m datasets itself? I even have thinked about h36m datasets came from Adobe :(. I found h36m [here](https://www.stubbornhuang.com/511/) and moshed date from [HybrIK](https://github.com/Jeff-sjtu/HybrIK/issues/5), kindness Jeff btw.
6. Why remove `frame_` in MPI-INF-3DHP image path ref [here](https://github.com/open-mmlab/mmhuman3d/blob/49e15b0cafee06f2241c199ac97efcd4a6dea909/mmhuman3d/data/data_converters/spin.py#L65)? It raise `FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/mpi_inf_3dhp/S5/Seq2/imageFrames/video_7/frame_000368.jpg'` when you start your first SPIN training.

Finally, in case #53 occur, run 
`python` -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 tools/train.py ./configs/spin/resnet50_spin_pw3d.py --no-validate --work-dir ./work_dir --gpus 4 --launcher pytorch`

`2022-03-30 07:17:02,817 - mmhuman3d - INFO - Epoch [1][50/782]  lr_backbone: 3.000e-05 lr_head: 3.000e-05, eta: 5:46:10, time: 2.673, data_time: 0.355, memory: 3296, keypoints3d_loss: 0.9700, keypoints2d_loss: 0.1061, vertex_loss: 0.1511, smpl_pose_loss: 0.0978, smpl_betas_loss: 0.0287, camera_loss: 0.0000, loss: 1.3538`

The world is bright again.

**Comment by caizhongang** [comment]
Hi @ykk648 , thank you very much for your feedback.

> 2. MPII official dataset missing `train.h5`, see #135 
We are looking into this, will update here if we have any progress.
> 3. MPI-INF-3DHP & Human3.6m needs extract frame first, I add `extract_img=True` in `convert_datasets.py`, it costs about 16 & 6 hours with low cpu consumation on one hard disk, no one had told me that :( 
> 4. According [human36m-mosh](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/preprocess_dataset.md#human36m-mosh), the file structure is `/datasets/h36m_mosh`, but the h36m_spin convertor acturally needs `/datasets/h36m_extras/mosh_data`
> 6. Why remove `frame_` in MPI-INF-3DHP image path ref [here](https://github.com/open-mmlab/mmhuman3d/blob/49e15b0cafee06f2241c199ac97efcd4a6dea909/mmhuman3d/data/data_converters/spin.py#L65)? It raise `FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/mpi_inf_3dhp/S5/Seq2/imageFrames/video_7/frame_000368.jpg'` when you start your first SPIN training.
These problems will be fixed in #143 .

> 5. Where is h36m datasets itself? I even have thinked about h36m datasets came from Adobe :(. I found h36m [here](https://www.stubbornhuang.com/511/) and moshed date from [HybrIK](https://github.com/Jeff-sjtu/HybrIK/issues/5), kindness Jeff btw.
To download H36M, you need to make an account at the [official website](http://vision.imar.ro/human3.6m/description.php) first and wait for approval. For H36M mosh, the original license does not allow us to redistribute it, but it is indeed available online.

**Comment by ykk648** [comment]
thx, issue close
