### ISSUE TITLE
[Feature] Add support for the STAR model

### ISSUE THREAD

**Issue by kristijanbartol** [open-mmlab/mmhuman3d#148]
Hi,

I would like to start contributing to this project. As we don't have a specific roadmap, I came up with a feature that seems reasonable - to add support for the [STAR model](https://star.is.tue.mpg.de/). I think it can be a good first feature to get to know the project and should prove useful as STAR is an improvement SMPL and can be used as a "drop-in replacement" for it.

Please let me know what you think.

**Comment by caizhongang** [comment]
Hi @kristijanbartol , awesome idea! Your contribution will be very much appreciated by the community! Please take a look at our contribution procedure [here](https://github.com/open-mmlab/mmhuman3d/blob/main/.github/CONTRIBUTING.md), and the STAR model may be placed at this [directory](https://github.com/open-mmlab/mmhuman3d/tree/main/mmhuman3d/models/body_models). Please let us know if any assitance is needed.

**Comment by kristijanbartol** [comment]
What actually bothers me are the licenses of these models. The original licenses for all MPI models are quite specific, for example, [the STAR license](https://github.com/ahmedosman/STAR/blob/master/LICENSE). They actually forbid the commercial use of their software, but the license of this repository is a commercial Apache 2.0.

I don't have any issues with the current licenses and I would gladly contribute with the STAR model if the licenses allow us to do so.

**Comment by caizhongang** [comment]
We do include [additional licenses](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/additional_licenses.md) in case the original models/algorithms have licenses that are more restrictive than ours.

**Comment by kristijanbartol** [comment]
I am trying to understand previously supported [body models](https://github.com/open-mmlab/mmhuman3d/tree/main/mmhuman3d/models/body_models). One of the constructor [arguments](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/models/body_models/smpl.py#L40) is a path to `joints_regressor`. I can see that one example of the numpy file can obtained from [here](https://github.com/open-mmlab/mmhuman3d/tree/main/configs/hmr). 

Did you create this data file or you downloaded it from some other repository? I can't recall whether I already saw it somewhere else.

**Comment by yl-1993** [comment]
Hi @kristijanbartol, basically what [isort](https://github.com/PyCQA/isort) does is to sort imports alphabetically.

In commit workflow, isort will solve the issue automatically and re-add the modified file to the commit will be good.
