### ISSUE TITLE
Keypoints overview for human_data

### ISSUE THREAD

**Issue by SizheAn** [open-mmlab/mmhuman3d#149]
Hi,

I'm trying to convert my own dataset to mmhuman3d format.

In https://github.com/open-mmlab/mmhuman3d/blob/main/docs/keypoints_convention.md it says `The first 144 keypoints in HumanData correspond to that in SMPL-X`. Are there any figures or plots for the visualization of these 144 keypoints? For example, in my dataset I have spine_base, spine_mid, and spine_shoulder. In human_data there are spine_1, spine_2, and spine_3 but I don't know the correspondences. A figure or plot can help me do that. Thanks!

**Comment by SizheAn** [comment]
Found the SMPL overview here https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf

Didn't find smpl-x 144 joints but the smpl one explains what spine_1, 2, and 3 is.

**Comment by caizhongang** [comment]
Hi @SizheAn , I think it is quite useful to include the plot for keypoint conventions, would you mind adding this request in [wishlist](https://github.com/open-mmlab/mmhuman3d/discussions/47)?

**Comment by caizhongang** [comment]
# SMPL-X
![smplx](https://user-images.githubusercontent.com/62529255/163091084-9c4e0922-b620-4026-8adf-721e5f71de8e.png)
![smplx-side](https://user-images.githubusercontent.com/62529255/163091170-e839324d-65b1-48e1-a3ec-ee1bd6810cbe.png)

# SMPL-X Face
![smplx-face](https://user-images.githubusercontent.com/62529255/163091241-594f7882-1eba-4674-b040-c7711f9f5814.png)
![smplx-head-side](https://user-images.githubusercontent.com/62529255/163091183-02f1a461-6eea-4b48-b1db-ab2ed86c3b8b.png)

# SMPL-X Left Hand
![smplx-left-hand](https://user-images.githubusercontent.com/62529255/163091272-e9224f88-1e64-41a9-a654-832839d68c38.png)

# SMPL-X Right Hand
![smplx-right-hand](https://user-images.githubusercontent.com/62529255/163091299-96c46be6-b7c4-4bc6-aea0-d8b41454d111.png)

**Comment by SizheAn** [comment]
> # SMPL-X
> ![smplx](https://user-images.githubusercontent.com/62529255/163091084-9c4e0922-b620-4026-8adf-721e5f71de8e.png) ![smplx-side](https://user-images.githubusercontent.com/62529255/163091170-e839324d-65b1-48e1-a3ec-ee1bd6810cbe.png)
> 
> # SMPL-X Face
> ![smplx-face](https://user-images.githubusercontent.com/62529255/163091241-594f7882-1eba-4674-b040-c7711f9f5814.png) ![smplx-head-side](https://user-images.githubusercontent.com/62529255/163091183-02f1a461-6eea-4b48-b1db-ab2ed86c3b8b.png)
> 
> # SMPL-X Left Hand
> ![smplx-left-hand](https://user-images.githubusercontent.com/62529255/163091272-e9224f88-1e64-41a9-a654-832839d68c38.png)
> 
> # SMPL-X Right Hand
> ![smplx-right-hand](https://user-images.githubusercontent.com/62529255/163091299-96c46be6-b7c4-4bc6-aea0-d8b41454d111.png)

Amazing! Thanks Zhongang, this is quite helpful. I will add it to the wishlist later.
