### ISSUE TITLE
why inference results look so shriveled

### ISSUE THREAD

**Issue by bixueting** [open-mmlab/mmhuman3d#16]
![Screenshot from 2021-12-07 16-18-45](https://user-images.githubusercontent.com/39902958/144992698-f6829a16-d1d2-40a0-b62a-e610142ad8bc.png)

**Comment by JasonBoy1** [comment]
This is due to the WeakperspectiveCameras. The vertices are computed to make the human mesh aligned to the original image. I think I can change this before rendering.

**Comment by JasonBoy1** [comment]
solved in PR#12, please have a look
