### ISSUE TITLE
just rethinking  [ convert agora data and visual smpl is wrong? #124 ]

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmhuman3d#163]
OK  sorry. I found not how to reopen the closed issue. so let us rethink it

**Comment by caizhongang** [comment]
Hi @Gzzgz , do you need me to reopen #124 ?

**Comment by Gzzgz** [comment]
@caizhongang yes. THX for your work. But I found some problems. Let's do it

**Comment by caizhongang** [comment]
#124 reopened.

**Comment by Gzzgz** [comment]
OK THX
