### ISSUE TITLE
ImportError: cannot import name 'axis_angle_to_quaternion' from 'pytorch3d.transforms' (/home/user/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/pytorch3d/transforms/__init__.py)

### ISSUE THREAD

**Issue by tianrking** [open-mmlab/mmhuman3d#17]
ImportError: cannot import name 'axis_angle_to_quaternion' from 'pytorch3d.transforms' (/home/user/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/pytorch3d/transforms/__init__.py)

(open-mmlab) root@slave01:~/lol/mmhuman3d# conda list
# packages in environment at /home/user/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
async-timeout             4.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
autobahn                  21.11.1                  pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.10.26           h06a4308_2    defaults
cdflib                    0.3.20                   pypi_0    pypi
certifi                   2021.10.8        py38h06a4308_0    defaults
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
colorlog                  6.6.0                    pypi_0    pypi
colormap                  1.0.4                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cryptography              36.0.0                   pypi_0    pypi
cudatoolkit               10.0.130                      0    defaults
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.25                  pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
dotty-dict                1.3.0                    pypi_0    pypi
easydev                   0.12.0                   pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0    defaults
flake8                    4.0.1                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
fonttools                 4.28.3                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0    defaults
frozenlist                1.2.0                    pypi_0    pypi
fvcore                    0.1.5.post20211023          pypi_0    pypi
giflib                    5.2.1                h7b6447c_0    defaults
gmp                       6.2.1                h2531618_2    defaults
gnutls                    3.6.15               he1e5248_0    defaults
h5py                      3.6.0                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.13.2                   pypi_0    pypi
incremental               21.3.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
iopath                    0.1.9                    pypi_0    pypi
jpeg                      9b                            0    defaults
json-tricks               3.15.5                   pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libidn2                   2.3.2                h7f8727e_0    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libuv                     1.40.0               h7b6447c_0    defaults
libvpx                    1.7.0                h439df22_0    defaults
libwebp                   1.2.0                h89dd481_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
matplotlib                3.5.0                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h7f8727e_0    defaults
mkl_fft                   1.3.1            py38hd3c417c_0    defaults
mkl_random                1.2.2            py38h51133e4_0    defaults
mmcls                     0.17.0                   pypi_0    pypi
mmcv-full                 1.3.18                   pypi_0    pypi
mmdet                     2.19.0                   pypi_0    pypi
mmhuman3d                 0.3.0                     dev_0    <develop>
mmpose                    0.21.0                   pypi_0    pypi
mmtrack                   0.8.0                    pypi_0    pypi
motmetrics                1.2.0                    pypi_0    pypi
multidict                 5.2.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2           py38hd09550d_3    defaults
numpy                     1.21.2           py38h20f2e39_0    defaults
numpy-base                1.21.2           py38h79a1101_0    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
opencv-python             4.5.4.60                 pypi_0    pypi
openh264                  2.1.0                hd408876_0    defaults
openssl                   1.1.1l               h7f8727e_0    defaults
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pillow                    8.4.0            py38h5aabda8_0    defaults
pip                       21.2.4           py38h06a4308_0    defaults
pluggy                    1.0.0                    pypi_0    pypi
portalocker               2.3.2                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pycocotools               2.0.3                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pytest                    6.2.5                    pypi_0    pypi
pytest-benchmark          3.4.1                    pypi_0    pypi
python                    3.8.12               h12debd9_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.8.0               py3.8_cpu_0  [cpuonly]  pytorch
pytorch3d                 0.3.0                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h27cfd23_0    defaults
scikit-image              0.19.0                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0    defaults
setuptools-scm            6.3.2                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0    defaults
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0    defaults
tabulate                  0.8.9                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminaltables            3.1.7                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.11               h1ccaba5_0    defaults
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.2                    pypi_0    pypi
torchvision               0.9.0                  py38_cpu  [cpuonly]  pytorch
tqdm                      4.62.3                   pypi_0    pypi
twisted                   21.7.0                   pypi_0    pypi
txaio                     21.2.1                   pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
vedo                      2021.0.7                 pypi_0    pypi
vtk                       9.0.3                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1    defaults
wrapt                     1.13.3                   pypi_0    pypi
wslink                    1.2.0                    pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0    defaults
xmltodict                 0.12.0                   pypi_0    pypi
xtcocotools               1.10                     pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
yacs                      0.1.8                    pypi_0    pypi
yapf                      0.31.0                   pypi_0    pypi
yarl                      1.7.2                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zope-interface            5.4.0                    pypi_0    pypi
zstd                      1.4.9                haebb681_0    defaults

**Comment by JasonBoy1** [comment]
Could you do this? 
```shell
echo "import torch;device=torch.device('cuda');\
    from pytorch3d.utils import torus;\
    Torus = torus(r=10, R=20, sides=100, rings=100, device=device);\
    print(Torus.verts_padded());"|python
```

Maybe you have not install3d pytorch3d right.

**Comment by JasonBoy1** [comment]
Please install the rely libs and use conda install

**Comment by JasonBoy1** [comment]
This will be closed if no further information.
