### ISSUE TITLE
Need to add `img_res = 224` in PARE config to run `demo/estimate_smpl.py`

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmhuman3d#172]

**Comment by WYJSJTU** [comment]
Thanks for your advice and it works. Maybe you can open a pull request to fix this issue?

**Comment by ykk648** [comment]
#176

**Comment by zetyquickly** [comment]
Hello, my I add here for some clarification.

Does PARE predicts `WeakPerspectiveCamera` parameters rather than `PerspectiveCamera`? If so, should `demo/estimate_smpl.py` call for `visualize_smpl_vibe`  instead `visualize_smpl_hmr`?
