### ISSUE TITLE
Got FBX&BVH output, how to get accurate body root `trans`?

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmhuman3d#177]
My script [fbx_output_mmhuman3d.py](https://github.com/ykk648/AI_power/blob/dev/mocap_lib/fbx_convert/fbx_output_mmhuman3d.py)  reference [vibe](https://github.com/mkocabas/VIBE#fbx-and-gltf-output-new-feature)

```
apt-get install blender
blender -b -P fbx_output_mmhuman3d.py
```

My output in blender ( despite some axes error ) :

![image1](https://user-images.githubusercontent.com/19514053/167568086-276fbfd3-ba8e-48f1-ac7d-c1822d8c1415.png)

This is BVH export from FBX, left is results without root `trans` , root can not move,  right is normal :
![image2](https://user-images.githubusercontent.com/19514053/167567883-7a318f53-b137-4863-983a-85ebd99708e0.png)

How can I get accurate `trans` to make the root moves?

**Comment by ykk648** [comment]
it seems problem solved, by using `pred_cam` to replace trans,  ref [ROMP](https://github.com/Arthur151/ROMP/issues/210)

**Comment by ypilseong** [comment]
@ykk648 
Could you tell me how to animate 3 people's video result npz file in blender? I don't have much information and I'm inexperienced, so I'd appreciate your help.

**Comment by ykk648** [comment]
@ypilseong I don't know that how to animate 3 people at the same time, my example is single person as you can see.

**Comment by ykk648** [comment]
It's a bit general, I dont know what problom you encountered specifically, you can try using my scripts mentioned above and search about `python blender fbx`
