### ISSUE TITLE
cam_param is absent in HumanData.SUPPORTED_KEYS.

### ISSUE THREAD

**Issue by YongtaoGe** [open-mmlab/mmhuman3d#18]
I want to convert Human36M dataset and I use the following script
```
python tools/convert_datasets.py --datasets h36m_p1 --root_path ../data/datasets/ --output_path ../data/processed_datasets
```
Then I get the error "cam_param is absent in HumanData.SUPPORTED_KEYS."

**Comment by YongtaoGe** [comment]
How can I get the following structure data of processed h36m mentioned in https://github.com/open-mmlab/mmhuman3d/blob/main/docs/preprocess_dataset.md#human36m
```
mmhuman3d
├── mmhuman3d
├── docs
├── tests
├── tools
├── configs
└── data
    └── datasets
        └── h36m
            ├── annot
            ├── S1
            |   ├── images
            |   |    |── S1_Directions_1.54138969
            |   |    |  ├── S1_Directions_1.54138969_00001.jpg
            |   |    |  ├── S1_Directions_1.54138969_00002.jpg
            |   |    |  └── ...
            |   |    └── ...
            |   ├── ...
            |   ├── MyPoseFeatures
            |   ├── MySegmentsMat
            |   └── Videos
            ├── S5
            ├── S6
            ├── S7
            ├── S8
            ├── S9
            ├── S11
            └── metadata.xml
```

**Comment by caizhongang** [comment]
Hello @YongtaoGe , for Human3.6M, you may download the original data from this [link](http://vision.imar.ro/human3.6m/description.php) and arrange it into the structure as shown above. 

Alternatively, you may download the preprocessed files directly, and the details can be found in [data preparation](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/preprocess_dataset.md#human36m).

**Comment by YongtaoGe** [comment]
@caizhongang, I want to get the images with downsampled frame rate (10 FPS) which are not provided in this repository. So I still need to run the preprocessing script, is it right?

**Comment by pangyyyyy** [comment]
Hi @YongtaoGe, 

Thanks for pointing it out, we will update our documentation in the future for better clarity.

For now:

To get the contents under "MyPoseFeatures", extract the following files that you have:
`tar zvxf Poses_D2_Positions_S1.tgz"
`tar zvxf Poses_D2_Positions_S1.tgz"

To get "MySegmentsMat",  download them as well (the h36m website calls them "Segments BBoxes MAT") and unpack them

To get the contents under "Videos", 
`tar zvxf Videos_S1.tgz"

You seem to be missing `metadata.xml` which you can get from the h36m website or [here](https://github.com/anibali/h36m-fetch/blob/master/metadata.xml).

To get the images:
please modify the DATASET_CONFIG in tools/convert_datasets.py to this:
```
    h36m_p1=dict(
        type='H36mConverter',
        modes=['train', 'valid'],
        protocol=1,
        extract_img=True,  # this is to specify you want to extract images from videos
        # mosh_dir='data/datasets/h36m_mosh', # comment this out if you do not have mosh
        prefix='h36m')
```
Rerun the same command as before and you should get the "images" folder:
```text
mmhuman3d
├── mmhuman3d
├── docs
├── tests
├── tools
├── configs
└── data
    └── datasets
        └── h36m
            ├── annot
            ├── S1
            |   ├── images
            |   |    |── S1_Directions_1.54138969
            |   |    |  ├── S1_Directions_1.54138969_00001.jpg
            |   |    |  ├── S1_Directions_1.54138969_00002.jpg
            |   |    |  └── ...
            |   |    └── ...
            |   ├── MyPoseFeatures
            |        |── D2Positions
            |        └── D3_Positions_Mono
            |   ├── MySegmentsMat
            |        └── ground_truth_bs
            |   └── Videos
            |        |── Directions 1.54138969.mp4
            |        |── Directions 1.55011271.mp4
            |        └── ...
            ├── S5
            ├── S6
            ├── S7
            ├── S8
            ├── S9
            ├── S11
            └── metadata.xml
```

**Comment by YongtaoGe** [comment]
@pangyyyyy Thank you very much! I will have a try.

**Comment by YongtaoGe** [comment]
There seems a bug in this line.

https://github.com/open-mmlab/mmhuman3d/blob/0a13943265ce0a74d206f4cfed6e9ca8726123a4/mmhuman3d/data/data_converters/h36m.py#L319

**Comment by leng-yue** [comment]
Did you solve this problem? I can still see the `cam_param is absent in HumanData.SUPPORTED_KEYS.` in the newest version.
