### ISSUE TITLE
The cmu_mosh.npz file sees broken

### ISSUE THREAD

**Issue by iceload123** [open-mmlab/mmhuman3d#19]
The Download link of cmu_mosh.npz from https://github.com/open-mmlab/mmhuman3d/blob/main/docs/preprocess_dataset.md Seems broken .....

"zipfile.BadZipFile: File is not a zip file" occurs when running an experiment  as well as when directly using numpy to load....

It's noticed that the size of the file is much smaller than the original one provided in https://github.com/open-mmlab/mmpose/blob/master/docs/tasks/3d_body_mesh.md

I Guess maybe the file is uncarefully overwritten.....

**Comment by caizhongang** [comment]
Hi iceload123, thank you for pointing it out, the link is updated in https://github.com/open-mmlab/mmhuman3d/pull/21.
