### ISSUE TITLE
Could you release the smoothnet training code?

### ISSUE THREAD

**Issue by qinb** [open-mmlab/mmhuman3d#192]
Thanks for your releasing the SmoothNet inference code and pre-trained model. And I want to ask when you plan to release the training code? Thanks again @yl-1993

**Comment by juxuan27** [comment]
Hi, @qinb! Thank you for your focus. We plan to release the training code of SmoothNet [here](https://github.com/cure-lab?type=source) this month. After this, we will add the training code into MMHuman3D. Please follow our future updates.

**Comment by qinb** [comment]
Thanks, I can't wait.
