### ISSUE TITLE
How to obtain the GTA-Human dataset?

### ISSUE THREAD

**Issue by xjchao7** [open-mmlab/mmhuman3d#215]
Thank you very much for your perfect work. I'm very interested in the GTA-Human dataset. I filled the form but got no response.  Could you please provide download link. 

Thank you very much.

**Comment by caizhongang** [comment]
@xjchao7 Thank you for your interest in GTA-Human! We have released the dataset [here](https://github.com/open-mmlab/mmhuman3d/tree/main/configs/gta_human). We will send out emails to people who have filled the form after we update the arXiv paper to its latest version.

**Comment by Xianjin111** [comment]
> @xjchao7 Thank you for your interest in GTA-Human! We have released the dataset [here](https://github.com/open-mmlab/mmhuman3d/tree/main/configs/gta_human). We will send out emails to people who have filled the form after we update the project Homepage.

Thank you so so much!

**Comment by xjchao7** [comment]
> @xjchao7 Thank you for your interest in GTA-Human! We have released the dataset [here](https://github.com/open-mmlab/mmhuman3d/tree/main/configs/gta_human). We will send out emails to people who have filled the form after we update the project Homepage.

Thanks so much!
