### ISSUE TITLE
FileNotFoundError gaus1d.py

### ISSUE THREAD

**Issue by Fubuki901** [open-mmlab/mmhuman3d#223]
Hi, you made a small mistake on a filename.
It should be ```./mmhuman3d/configs/_base_/post_processing/gaus1d.py``` but not ```guas1d.py``` which may cause FileNotFoundError when setting ``` --smooth_type gaus1d```
Please check it.
And also it's wrong name in the ```getting_started.md``` at Inference part.

**Comment by caizhongang** [comment]
@Fubuki901 Thank you for pointing it out! Would you like to contribute a PR to correct them?

**Comment by Fubuki901** [comment]
@caizhongang Done

**Comment by ttxskk** [comment]
Hi @juxuan27,
#232 seems not to merge into the main branch, please check it.
BTW, In PR #232 the docs_zh-CN should also be updated.
