### ISSUE TITLE
running demo - mmdet not installed

### ISSUE THREAD

**Issue by iulsko** [open-mmlab/mmhuman3d#226]
hi, even though i have mmdet installed i still get:

> Traceback (most recent call last):
>   File "demo/estimate_smpl.py", line 583, in <module>
>     assert has_mmdet, 'Please install mmdet to run the demo.'
> AssertionError: Please install mmdet to run the demo.

it was installed using these instructions - https://mmdetection.readthedocs.io/en/v2.2.0/install.html \
i have pytorch 1.8.0 and cuda 11.6.\
here is my environment:

_Name_                    _Version_                   _Build_  _Channel_
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
astropy                   5.1                      pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
autobahn                  22.6.1                   pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cdflib                    0.3.20                   pypi_0    pypi
certifi                   2022.6.15        py38h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.0                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
colorlog                  6.6.0                    pypi_0    pypi
colormap                  1.0.4                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cryptography              37.0.4                   pypi_0    pypi
cudatoolkit               11.6.0              hecad31d_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.30                  pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
easydev                   0.12.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.34.4                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0                    pypi_0    pypi
fvcore                    0.1.5.post20210915            py38    fvcore
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
h5py                      3.7.0                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.19.3                   pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
incremental               21.3.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
iopath                    0.1.9                      py38    iopath
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.4.3                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.17                 h166bdaf_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.2.0                h85742a9_0  
libuv                     1.43.0               h7f98852_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.7                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
mmcv-full                 1.5.3                    pypi_0    pypi
**mmdet                     2.25.0                    dev_0    <develop>**
mmhuman3d                 0.9.0                     dev_0    <develop>
mmpycocotools             12.0.3                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.8.4                    pypi_0    pypi
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.22.3           py38he7a7128_0  
numpy-base                1.22.3           py38hf524024_0  
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openmim                   0.2.0                    pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.1.2           py38h06a4308_0  
plyfile                   0.7.4                    pypi_0    pypi
portalocker               2.5.1            py38h578d9bd_0    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pycocotools               2.0.4                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.0               py3.8_cpu_0  [cpuonly]  pytorch
pytorch3d                 0.6.2                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0              py38h0a891b7_4    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.28.1                   pypi_0    pypi
rich                      12.5.1                   pypi_0    pypi
rtree                     1.0.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.38.5               hc218d9a_0  
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
terminaltables            3.1.10                   pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                  py38_cpu  [cpuonly]  pytorch
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
trimesh                   3.12.8                   pypi_0    pypi
twisted                   22.4.0                   pypi_0    pypi
txaio                     22.2.1                   pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
urllib3                   1.26.10                  pypi_0    pypi
vedo                      2022.2.3                 pypi_0    pypi
vtk                       9.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1                   pypi_0    pypi
wslink                    1.6.6                    pypi_0    pypi
xz                        5.2.5                h7f8727e_1  
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yapf                      0.32.0                   pypi_0    pypi
yarl                      1.7.2                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  
zope-interface            5.4.0                    pypi_0    pypi
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by ttxskk** [comment]
Hi, you can try `from mmdet.apis import inference_detector, init_detector`  in your conda environment directly, it might tell you the error you are facing.
From your provided environment info, I guess you can try updating your NumPy version from `v1.22.3` to `v1.23.0`.

**Comment by ttxskk** [comment]
Closing this issue as there is no more feedback.

**Comment by RuiZhang-USTC** [comment]
> from mmdet.apis import inference_detector, init_detector
~/mmhuman3d$ from mmdet.apis import inference_detector, init_detector
from: can't read /var/mail/mmdet.apis


and I have update numpy to 1.23.0, the demo still reports same erro
