### ISSUE TITLE
How to put H36M moshed data as mmhuman3d data structure

### ISSUE THREAD

**Issue by Fmin-Zou** [open-mmlab/mmhuman3d#231]
Hello，I want to train PARE with Human3.6M Mosh and I have get the h36m_train_mosh.npz. But I noticed that it requires me to put the Moshed data as the mentioned [structure,](https://mmhuman3d.readthedocs.io/en/latest/preprocess_dataset.html#human36m-mosh)
![图片](https://user-images.githubusercontent.com/60681528/179971371-7f34dc4c-18fd-4863-8947-ab60e4cbf7ce.png)
I'm confused that how can I get the Moshed data, and If I download the moshed data from [HMR,](https://github.com/akanazawa/hmr/blob/master/doc/train.md) how should I put them as the mentioned mmhuman3d h36m_mosh data structure.  Could you give some advice?

**Comment by WYJSJTU** [comment]
Unfortunately, we are not allowed to distribute the MoShed data due to the license limitations of Human3.6M. The Moshed data in [HMR](https://github.com/akanazawa/hmr) dosen't include Human3.6M Moshed data. So you may need to look for related shares in other open source repositories.

**Comment by Vegetebird** [comment]
@Fmin-Zou Hi~Could you share me the 'h36m_train_mosh.npz'? My wechat is: Vegetaberd or email is: 781256005@qq.com

**Comment by Fmin-Zou** [comment]
> @Fmin-Zou Hi~Could you share me the 'h36m_train_mosh.npz'? My wechat is: Vegetaberd or email is: [781256005@qq.com](mailto:781256005@qq.com)

I am sorry that I had some misunderstanding about the data before. Unfortunately, I  haven't got the moshed data.
