### ISSUE TITLE
SMPLX_NEUTURAL does not exists

### ISSUE THREAD

**Issue by zhewei-mt** [open-mmlab/mmhuman3d#236]
Hello,
I was trying to check out smplx update in the latest repo.
The code I was running is:
```
python estimate_smpl.py \
    configs/expose/expose.py \
    data/checkpoints/expose-d9d5dbf7_20220708.pth \
    --multi_person_demo \
    --tracking_config demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py \
    --input_path  demo/resources/cindy.mp4 \
    --show_path vis_results_zhewei_vibe/cindy_out.mp4 \
    --smooth_type savgol \
    --speed_up_type deciwatch \
    --draw_bbox
```
But an error popped out saying that "data/body_models/smplx/SMPLX_NEUTRAL.npz does not exist!"
And I don't find where to download SMPLX_NEUTRAL.npz. Anywhere that I can download this file?
Any help will be appreciate!

**Comment by mingyuan-zhang** [comment]
you can download from this website: https://smpl-x.is.tue.mpg.de/download.php

**Comment by zhewei-mt** [comment]
> you can download from this website: https://smpl-x.is.tue.mpg.de/download.php

Thanks a lot!
