### ISSUE TITLE
the mocap data generated from PARE were distorted when converting to fbx

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmhuman3d#245]
![image](https://user-images.githubusercontent.com/21303438/186343657-c2eb5f9d-f83f-4d21-a203-0f7b4d0cad31.png)

I converted the rotmat output to quaternion, the generate fbx in blender, the animation seems not right.

However, I can sucessfully gen animation from romp and hybrIK, does there any different from PARE?

I noticed the output is [23, 3] while ROMP and hybrIK is [24, 3], why PARE less one joint?

**Comment by jinfagang** [comment]
OK, I solved it.

**Comment by zetyquickly** [comment]
hey @jinfagang how do you apply predicted bone rotations when bones do not oriented vertically but along the body?

**Comment by jinfagang** [comment]
it's not about prediction, it's about your model.

**Comment by zetyquickly** [comment]
the whole project works against SMPL that has same bones oriented upwards like in your YBOT. have you applied predictions of PARE/HMR to the models that are rigged in the usual way, alongside the body limbs? how to map first to second?
