### ISSUE TITLE
Vibe converter

### ISSUE THREAD

**Issue by YongtaoGe** [open-mmlab/mmhuman3d#25]
When I try to convert insta_variety dataset, I get the following error:
```
Traceback (most recent call last):
  File "tools/convert_datasets.py", line 118, in <module>
    main()
  File "tools/convert_datasets.py", line 113, in main
    data_converter.convert(input_path, args.output_path)
  File "/mnt/share_1227775/yongtaoge/mmhuman3d/mmhuman3d/data/data_converters/insta_vibe.py", line 81, in convert
    features_ = np.array(features_).reshape((-1, 2048))
numpy.core._exceptions.MemoryError: Unable to allocate 16.7 GiB for an array with shape (2187158, 2048) and data type float32
```

**Comment by YongtaoGe** [comment]
I also cannot finder converter for 'vibe_mpi_inf_3dhp_train.npz'.

**Comment by caizhongang** [comment]
Hi @YongtaoGe, the links to the preprocessed files for vibe training will be updated shortly.

**Comment by pangyyyyy** [comment]
> When I try to convert insta_variety dataset, I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "tools/convert_datasets.py", line 118, in <module>
>     main()
>   File "tools/convert_datasets.py", line 113, in main
>     data_converter.convert(input_path, args.output_path)
>   File "/mnt/share_1227775/yongtaoge/mmhuman3d/mmhuman3d/data/data_converters/insta_vibe.py", line 81, in convert
>     features_ = np.array(features_).reshape((-1, 2048))
> numpy.core._exceptions.MemoryError: Unable to allocate 16.7 GiB for an array with shape (2187158, 2048) and data type float32
> ```

Hi @YongtaoGe,  how much memory do you have?

It seems like an issue with the RAM memory (insta_train_db.h5 is 18.1GB). Alternatively, we have provided the preprocessed npz files so you don't have to convert from raw. 

The converters for other vibe datasets i.e. 'vibe_mpi_inf_3dhp_train.npz' and 'vibe_pw3d_test.npz' will be added in the future.

**Comment by jinfagang** [comment]
@pangyyyyy I train on PARE with default dataset on 40GB mem also get similar error:

```
numpy.core._exceptions.MemoryError: Unable to allocate 7.91 GiB for an array with shape (1396913, 190, 4) and data type float64
```
