### ISSUE TITLE
How to inference from the 3D keypoints and SMPL parameter

### ISSUE THREAD

**Issue by yqtl** [open-mmlab/mmhuman3d#258]
Hi,
I have a data structure with 3D keypoints and corresponding SMPL parameters.
The 3D keypoints in the shape of [num_frame, num_joints, coordinates], and the corresponding estimated smpl parameters in the shape of [num_frame, 24, 3].
I can of course construct the data according to HumanData structure.
But I would like to use the SmoothNet module for post processing.
Is there a way to inference the MMhuman3D demo on the existing estimated poses?

**Comment by ttxskk** [comment]
Do you mean how to run SmoothNet on your own data? If so, you can run [smooth_process](https://github.com/open-mmlab/mmhuman3d/blob/6055d23961240a01c96a364fe2974020c7401f07/mmhuman3d/utils/demo_utils.py#L316) directly with your data, more details can be found in the [docstring](https://github.com/open-mmlab/mmhuman3d/blob/6055d23961240a01c96a364fe2974020c7401f07/mmhuman3d/utils/demo_utils.py#L319-L337) and our [demo](https://github.com/open-mmlab/mmhuman3d/blob/main/demo/estimate_smpl.py#L392-L399).

**Comment by yqtl** [comment]
Thanks, will try that. I was wondering this function https://github.com/open-mmlab/mmhuman3d/blob/6055d23961240a01c96a364fe2974020c7401f07/mmhuman3d/utils/demo_utils.py#L316
So it works with smpl array with shape [frame,num_person,K,C], but doe it also work with skeleton keypoints3d data?

**Comment by ttxskk** [comment]
> Thanks, will try that. I was wondering this function
> 
> https://github.com/open-mmlab/mmhuman3d/blob/6055d23961240a01c96a364fe2974020c7401f07/mmhuman3d/utils/demo_utils.py#L316
> 
> 
> So it works with smpl array with shape [frame,num_person,K,C], but doe it also work with skeleton keypoints3d data?

Yes, x can be SMPL parameters and kp3d.
