### ISSUE TITLE
validation per N epochs

### ISSUE THREAD

**Issue by linjing7** [open-mmlab/mmhuman3d#260]
Hi, I find that the validation procedure is quite time-consuming. Could you please tell me how to validate per N epochs, e.g. 5 epochs, instead of every epoch?

**Comment by ttxskk** [comment]
Hi @linjing7,
you can modify the config like:
```python
# evaluate
evaluation = dict(interval=N, metric=['pa-mpjpe', 'mpjpe'])
```

**Comment by linjing7** [comment]
Okay, thank you very much.
