### ISSUE TITLE
Failed to reproduce results of Hybrik

### ISSUE THREAD

**Issue by jder1234** [open-mmlab/mmhuman3d#267]
Hi,  @ttxskk 

I carried out my experiments following the README (config, data preparation, dataset processing),  however, there is a significant gap between my PA-MPJPE (53 ~54) and the PA-MPJPE (49.02) proposed in the README.

Here is my training log: 
[20221015_023230.log](https://github.com/open-mmlab/mmhuman3d/files/9809526/20221015_023230.log)

**Comment by jder1234** [comment]
The PA-MPJPE is reduced to 49.67 with the updated config.  the issue seems to be resolved. @ttxskk

**Comment by ttxskk** [comment]
Hi @jder1234,
Thanks for your feedback. Would you mind creating a PR to fix this?
