### ISSUE TITLE
AssertionError: Please install mmdet to run the demo But had installed mmdet

### ISSUE THREAD

**Issue by tianrking** [open-mmlab/mmhuman3d#27]
(open-mmlab) ➜  mmhuman3d git:(main) python demo/estimate_smpl.py \
    configs/hmr/resnet50_hmr_pw3d.py \
    data/checkpoints/resnet50_hmr_pw3d.pth \
    --single_person_demo \
    --det_config demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    --det_checkpoint https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ 
    --video_path  demo/resources/single_person_demo.mp4 \
    --output_path vis_results/single_person_demo.mp4 \
    --smooth_type savgol
Traceback (most recent call last):
  File "demo/estimate_smpl.py", line 286, in <module>
    assert has_mmdet, 'Please install mmdet to run the demo.'
AssertionError: Please install mmdet to run the demo.
(open-mmlab) ➜  mmhuman3d git:(main) conda list

(open-mmlab) ➜  mmhuman3d git:(main) conda list
# packages in environment at /home/w0x7ce/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
async-timeout             4.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
autobahn                  21.11.1                  pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h7f98852_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cdflib                    0.3.20                   pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlog                  6.6.0                    pypi_0    pypi
colormap                  1.0.4                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cryptography              36.0.0                   pypi_0    pypi
cudatoolkit               11.2.2               he111cf0_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.25                  pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
dotty-dict                1.3.0                    pypi_0    pypi
easydev                   0.12.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
flake8                    4.0.1                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
fonttools                 4.28.3                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
frozenlist                1.2.0                    pypi_0    pypi
fvcore                    0.1.5.post20210915            py38    fvcore
gmp                       6.2.1                h58526e2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gnutls                    3.6.13               h85f3911_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
h5py                      3.6.0                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.13.3                   pypi_0    pypi
incremental               21.3.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
iopath                    0.1.9                      py38    iopath
jpeg                      9b                   h024ee3a_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
json-tricks               3.15.5                   pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100             h7f98852_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   11.2.0              h1d223b6_11    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.16                 h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.37               h21135ba_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.2.0                h85742a9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuv                     1.42.0               h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.2.1                h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.11            h36c2ea0_1013    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib                3.5.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py38h95df7f1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl_fft                   1.3.1            py38h8666266_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl_random                1.2.2            py38h1abd341_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mmcls                     0.17.0                   pypi_0    pypi
mmcv-full                 1.3.18                   pypi_0    pypi
mmdet                     2.19.0                    dev_0    <develop>
mmhuman3d                 0.3.0                     dev_0    <develop>
mmpose                    0.21.0                   pypi_0    pypi
mmtrack                   0.8.0                    pypi_0    pypi
motmetrics                1.2.0                    pypi_0    pypi
multidict                 5.2.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nettle                    3.6                  he412f7d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.21.2           py38h20f2e39_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.21.2           py38h79a1101_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opencv-python             4.5.4.60                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pluggy                    1.0.0                    pypi_0    pypi
portalocker               2.3.2            py38h578d9bd_1    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pycocotools               2.0.3                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pytest                    6.2.5                    pypi_0    pypi
pytest-benchmark          3.4.1                    pypi_0    pypi
python                    3.8.12          hf930737_2_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.8.0               py3.8_cpu_0  [cpuonly]  pytorch
pytorch3d                 0.6.0                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0              py38h497a2fe_3    conda-forge
readline                  8.1                  h46c0cb4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scikit-image              0.19.0                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                59.4.0           py38h578d9bd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
setuptools-scm            6.3.2                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.37.0               h9cd32fc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminaltables            3.1.10                   pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.11               h27826a3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.2                    pypi_0    pypi
torchvision               0.9.0                  py38_cpu  [cpuonly]  pytorch
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
twisted                   21.7.0                   pypi_0    pypi
txaio                     21.2.1                   pypi_0    pypi
typing_extensions         4.0.1              pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vedo                      2021.0.7                 pypi_0    pypi
vtk                       9.0.3                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wrapt                     1.13.3                   pypi_0    pypi
wslink                    1.2.0                    pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xtcocotools               1.10                     pypi_0    pypi
xz                        5.2.5                h516909a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.31.0                   pypi_0    pypi
yarl                      1.7.2                    pypi_0    pypi
zlib                      1.2.11            h36c2ea0_1013    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zope-interface            5.4.0                    pypi_0    pypi
zstd                      1.4.9                ha95c52a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
(open-mmlab) ➜  mmhuman3d git:(main)

**Comment by ttxskk** [comment]
It seems that MMDetection was not installed successfully. Would you mind referring to [install.md](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/install.md) to reinstall it?

**Comment by caizhongang** [comment]
@tianrking May we know if your problem is solved?

**Comment by ZhengtianXu** [comment]
> @tianrking May we know if your problem is solved?

I also have this error. The pip shows Successfully installed mmdet-2.19.1

**Comment by ttxskk** [comment]
@ZhengtianXu Have you tried to reinstall `MMdet`?  
BTW, can you directly import `MMdet`  in your conda virtual environment?

**Comment by ZhengtianXu** [comment]
> @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?

yeah, I can import mmdet. If I `from mmdet.apis import inference_detector, init_detector`, it raises `anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv`

**Comment by ZhengtianXu** [comment]
> @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?

It solved with another version mmcv

**Comment by GQZxn** [comment]
请问解决这个问题了吗 
![image](https://user-images.githubusercontent.com/51876142/194053503-f89fc9b9-f509-428b-9401-733b04fb47f8.png)

**Comment by yt4766269** [comment]
> > @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?
> 
> It solved with another version mmcv

Which version of mmcv were you using?

**Comment by Taylorminer** [comment]
> > @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?
> 
> It solved with another version mmcv

@ZhengtianXu Which version of mmcv were you using?

**Comment by Qusong1** [comment]
> > @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?
> 
> It solved with another version mmcv

Hello, Which version of mmcv were you using?

**Comment by Qusong1** [comment]
> > > @ZhengtianXu Have you tried to reinstall `MMdet`? BTW, can you directly import `MMdet` in your conda virtual environment?
> > 
> > 
> > It solved with another version mmcv
> 
> @ZhengtianXu Which version of mmcv were you using?

Hello, could you tell me you have also solved the problem yet? if you have solved it, could you tell me the way? Thank you very much!

**Comment by RuiZhang-USTC** [comment]
changing version of mmcv and still the same error
