### ISSUE TITLE
Typo in keypoints_convention.md

### ISSUE THREAD

**Issue by syguan96** [open-mmlab/mmhuman3d#29]
Thanks for your contribution to the community!
I found a typo in the `keypoints_convention.md`:
```
keypoints = np.zeros((1, len(KEYPOINTS_FACTORY['smpl']), 3))
original_mask = np.ones((len(KEYPOINTS_FACTORY['smpl'])))
original_mask[KEYPOINTS_FACTORY['smpl'].index('left_hip')] = 0

_, mask_coco = convert_kps(
    keypoints=keypoints, mask=original_mask, src='smpl', dst='coco')
_, mask_coco_full = convert_kps(
    keypoints=keypoints, src='smpl', dst='coco')

assert mask_coco[KEYPOINTS_FACTORY['coco'].index('left_hip')] == 0
mask_coco[KEYPOINTS_FACTORY['coco'].index('left_hip')] = 1
assert (mask_coco == mask_coco_full).all()
```
`KEYPOINTS_FACTORY['coco']` doesn't have `left_hip` joint. Maybe `coco` could be changed to `agora`.

Also, I have a suggestion here. We usually not only convert coordinates of the skeleton but also pass the confidence of each joint together. when I changed to `original_mask[KEYPOINTS_FACTORY['smpl'].index('left_hip')] = 0.5`, the converted mask is also `0`. So, I think return converted order (indices) instead of the converted skeleton is more flexible and convenient.

**Comment by syguan96** [comment]
Maybe there is another typo in [cameras.py](https://github.com/open-mmlab/mmhuman3d/blob/0cb4a56576b7c69ec72f756b931b3a67674a9ba6/mmhuman3d/core/cameras/cameras.py#L139)

**Comment by JasonBoy1** [comment]
Thank you for your information! This will be fixed in next PR. I will @ you when it is ready.

**Comment by JasonBoy1** [comment]
> 

About your question "when I changed to `original_mask[KEYPOINTS_FACTORY['smpl'].index('left_hip')] = 0.5`, the converted mask is also 0". I recommend you that you pass the keypoints with the confidence concatenated at the last channel. 

```python
original_mask[KEYPOINTS_FACTORY['smpl'].index('left_hip')] = 0.5
kp_smpl = np.concatenate([kp_smpl, original_mask], -1)
convert_kps(kp_smpl, src='smpl', dst=dst)
```

**Comment by syguan96** [comment]
Thanks! Its works for me.
