### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by caizhongang** [open-mmlab/mmhuman3d#3]
Please leave a comment on what new method/feature/dataset you would like us to add in MMHuman3D. 

The most upvoted suggestions will be prioritized!

**Comment by YuliangXiu** [comment]
Given the name "mmhuman3d", there is no reason to include only body under clothing. Please check [HERE](https://project-splinter.github.io/).

**Comment by rlleshi** [comment]
Converting the output to `.fbx` format.

**Comment by puppet101** [comment]
new SOTA works, such as https://www.ye-yuan.com/glamr, the result in the video is amazing good

**Comment by ChristianIngwersen** [comment]
Updated documentation to document how to do inference on a custom dataset. 
Or maybe changing the `estimate_smpl.py` demo to also outputting a results file

**Comment by vra** [comment]
new SOTA method [PARE](https://arxiv.org/abs/2104.08527)

**Comment by syguan96** [comment]
I agree Yuliang's option. Also, works about expressive body estimation are necessary to be included for completeness.

**Comment by Walter0807** [comment]
Hi, could you please release the converted amass.npz? Thanks!

**Comment by caizhongang** [comment]
Thank you all for your suggestions! The development team has been paying close attention to the community feedback and we will release our roadmap towards next major update for MMHuman3D soon! 

We have moved our Wishlist to this [discussion](https://github.com/open-mmlab/mmhuman3d/discussions/47). See you there!
