### ISSUE TITLE
camera.md may explain more on perspective cameras

### ISSUE THREAD

**Issue by caizhongang** [open-mmlab/mmhuman3d#33]
- principle_points are not defined in [example](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/cameras.md#camera-initialize).
- example for focal length may also be included.
- in_ndc needs some explanation for CV people who may not be familiar.
- [`cameras`](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/cameras.md#some-compute-functions) -> `cam` as here we have only one camera and `cam` is used in examples above.

**Comment by JasonBoy1** [comment]
#32

**Comment by caizhongang** [comment]
Addressed in #32
