### ISSUE TITLE
AssertionError: Please install mmtrack to run the demo.

### ISSUE THREAD

**Issue by Rook1e-li** [open-mmlab/mmhuman3d#335]
Traceback (most recent call last):
  File "demo/estimate_smpl.py", line 590, in <module>
    assert has_mmtrack, 'Please install mmtrack to run the demo.'
AssertionError: Please install mmtrack to run the demo. 

I already installed the mmtrack, and the version is 0.13.0.  The version of 0.14.0 is not working as well

**Comment by Rook1e-li** [comment]
It was happed when I want to inference video with multi-person. 
Here is the code
python demo/estimate_smpl.py \
configs/cliff/resnet50_pw3d_cache.py \
data/checkpoints/resnet50_cliff_new-1e639f1d_20230327.pth \
    --multi_person_demo \
    --tracking_config demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py \
    --input_path  demo/resources/multi_person_demo.mp4 \
    --show_path vis_results/multi_person_demo.mp4 \
    --smooth_type savgol \
    --speed_up_type deciwatch \
    --draw_bbox

**Comment by SWWdz** [comment]
How to solve the problem? Thanks.

**Comment by Whiplash-18** [comment]
> How to solve the problem? Thanks.

have you resolved the problem
