### ISSUE TITLE
Please release the converted amass.npz

### ISSUE THREAD

**Issue by caizhongang** [open-mmlab/mmhuman3d#49]
Hi, could you please release the converted amass.npz? Thanks!

_Originally posted by @Walter0807 in https://github.com/open-mmlab/mmhuman3d/issues/3#issuecomment-995879023_

**Comment by pangyyyyy** [comment]
Hi @Walter0807 These are links for the converted amass npz files containing smplh and smplx annotations (sampled at 10 fps)

amass_smplh.npz
https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmhuman3d/datasets/amass_smplh.npz?versionId=CAEQIhiBgICS4Mrt7xciIGU5MDBmZmE4Y2I0NjRiYTc4ZWY2NzY2MzU1ZmIwZTQ2

amass_smplx.npz
https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmhuman3d/datasets/amass_smplx.npz?versionId=CAEQIhiBgIDh387t7xciIGRlN2JlZjA0ZGM0YzRkNmM5OWJhNmVjMmZlN2RiN2E1

```
smplh_sequences = [
    'ACCAD',
    'BioMotionLab_NTroje',
    'CMU',
    'EKUT',
    'Eyes_Japan_Dataset',
    'HumanEva',
    'KIT',
    'MPI_HDM05',
    'MPI_Limits',
    'MPI_mosh',
    'SFU',
    'SSM_synced',
    'TCD_handMocap',
    'TotalCapture',
    'Transitions_mocap',
]

smplx_sequences = [
    'ACCAD',
    'BMLmovi',
    'BMLrub',
    'CMU',
    'DanceDB',
    'DFaust',
    'EKUT',
    'Eyes_Japan_Dataset',
    'HDM05',
    'HumanEva',
    'KIT',
    'MoSh',
    'PosePrior',
    'SFU',
    'SSM',
    'TCDHands',
    'TotalCapture',
    'Transitions',
]
```

**Comment by caizhongang** [comment]
Links added in #69 . Close issue now.
