### ISSUE TITLE
A Tiny Bug in agora data convertor

### ISSUE THREAD

**Issue by iceload123** [open-mmlab/mmhuman3d#67]
In https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/agora.py#L108, it is expected to add resolution endfix to image path when res = (1280,720).  However, "replace" is not a in-place operation....

**Comment by iceload123** [comment]
Another small bug:
https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/agora.py#L121

It should be (1280,720)

**Comment by iceload123** [comment]
I also find that, for posetrack dataset,
https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/posetrack.py#L53

assumes that "images" and "annotations" are aligned, which is not true. There is a shift as "annotations" only contains labeled frames

**Comment by iceload123** [comment]
> https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/posetrack.py#L53

I re-check the json format. "annotations" are instance-wise annotations while "images" are image-wise metas.

**Comment by iceload123** [comment]
Another small bug in Surreal dataset:
dump image index starts from 1, while image path index starts from 0

https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/surreal.py#L187

**Comment by pangyyyyy** [comment]
@iceload123 Thanks for pointing out the bugs! These will be fixed shortly
