### ISSUE TITLE
Typo and potential bugs in data converter 

### ISSUE THREAD

**Issue by caizhongang** [open-mmlab/mmhuman3d#70]
1. [`bbox_xywh`](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/pw3d.py#L100) here is actually `bbox_xyxy`
2. [`_bbox_expand()`](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/base_converter.py#L27) should not perform `bbox_xyxy -> bbox_xywh` as this is not reflected in the name. 
3. [`_bbox_expand()`](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/base_converter.py#L27) does not constrain the bbox to be within the image after expansion (i.e. 0 <= x < width, 0 <= y < height)
4. `bbox_xyxy -> bbox_xywh` may consider reusing this [code](https://github.com/open-mmlab/mmhuman3d/blob/af3b750ed8918d6a33097eec01e2c9fbbf15b17d/mmhuman3d/utils/demo_utils.py#L17) as it also supports batch conversion.

May be addressed in #69 .

**Comment by pangyyyyy** [comment]
@caizhongang 
2. [`_bbox_expand()`](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/base_converter.py#L27) performs `bbox_xyxy -> bbox_xywh` and the bbox is expanded by the specified scale factor. 
4. This [code](https://github.com/open-mmlab/mmhuman3d/blob/af3b750ed8918d6a33097eec01e2c9fbbf15b17d/mmhuman3d/utils/demo_utils.py#L17) is neat but it doesn't include the bbox expansion

**Comment by caizhongang** [comment]
> @caizhongang
> 
> [`_bbox_expand()`](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/base_converter.py#L27) performs `bbox_xyxy -> bbox_xywh` and the bbox is expanded by the specified scale factor. This [code](https://github.com/open-mmlab/mmhuman3d/blob/af3b750ed8918d6a33097eec01e2c9fbbf15b17d/mmhuman3d/utils/demo_utils.py#L17) is neat but it doesn't include the bbox expansion. Should `_bbox_expand` be renamed for better clarity?

I think bbox_expand() can be pulled out as a function instead of a static method, and put in the same file as the `bbox_xyxy->bbox_xywh`. The data converters may just import both to process data.
