### ISSUE TITLE
Reproduce HMR result

### ISSUE THREAD

**Issue by panshaohua** [open-mmlab/mmhuman3d#72]
Hi. Thanks your work. Could you tell me something wrong with my training log about reproducing HMR result?
This is my log.
[20220107_150016.log](https://github.com/open-mmlab/mmhuman3d/files/7836486/20220107_150016.log)

![image](https://user-images.githubusercontent.com/16032408/148711290-a07f70b5-02a3-47c3-9413-a397d0b3af16.png)

**Comment by caizhongang** [comment]
Hi @panshaohua , several bugs have been fixed since then, please use the latest main and try again.
