### ISSUE TITLE
HumanData does not support concat and slice

### ISSUE THREAD

**Issue by caizhongang** [open-mmlab/mmhuman3d#75]
- concat HumanData, e.g. `human_data_concat = HumanData.concatenate([human_data_1, human_data_2])`
- slice HumanData, e.g. `human_data_slice = human_data[:10]`

**Comment by LazyBusyYang** [comment]
Slice is supported in the current version, see details below:
https://github.com/open-mmlab/mmhuman3d/blob/main/docs/human_data.md#select-temporal-slice
Do remember that only keys in `SUPPORTED_KEYS` with `temporal_dim` defined will be correctly sliced.

Concat will come in the future.

**Comment by caizhongang** [comment]
I'm aware of the temporal slicing, but with 2 issues：
- SMPL parameters are not sliced.
- it is not necessarily the "temporal" dimension that we want to slice, the naming may be to specific. `slice_dimension` may be better, and all parameters should have the first dimension as the default slice dimension (if can be sliced)

**Comment by LazyBusyYang** [comment]
Concat is added in the PR below:
https://github.com/open-mmlab/mmhuman3d/pull/126
