### ISSUE TITLE
about spin pre_data

### ISSUE THREAD

**Issue by zhangzhenyu-zzy** [open-mmlab/mmhuman3d#82]
I noticed that in the original code of spin, one is taken every 5 frames, while in this framework, the processing h36m is taken every 10 frames. I want to know this h36m_fits.npy obtained every 10 frames or 5 frames? Is it consistent with spin source code？

**Comment by pangyyyyy** [comment]
Hi @zhangzhenyu-zzy, are you referring to the processing of `spin_h36m_train.npz` and `h36m_train.npz`? 

Our current preprocessing takes every 5 frames (https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/data_converters/h36m_spin.py#L170), which is consistent with spin preprocessing (https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/h36m_train.py#L76).
