### ISSUE TITLE
目前mmhuman3d支持对深度数据的估算吗 | Does mmhuman3d support depth data

### ISSUE THREAD

**Issue by socketing** [open-mmlab/mmhuman3d#84]
很高兴看到这么伟大的开源。在这里我希望用母语来询问。我想知道这个开源支持从传感器传入深度数据或者点云数据来生成参数化模型吗？这样可以更直接的对人体尺寸进行估算，毕竟2d估算的尺寸并不正确。
希望可以得到你们的回答

---

Translation: Will this codebase support depth / point-cloud data for parametric model estimation? This will provide an accurate dimension estimation of human subjects given that estimation from 2D data can be ambiguous.

**Comment by caizhongang** [comment]
@socketing 你好，基于深度学习的算法已经提上日程，相信在今年上半年就会加入代码库。更多进展请关注：[Roadmap](https://github.com/open-mmlab/mmhuman3d/discussions/48#discussion-3763206)

另外，如果不介意的话我们会给问题加上英文，方便更多的用户从你的问题中受益。

---

Translation: point cloud-based methods are under development and will be added in MMHuman3D by 2022 H1. Please check our [Roadmap](https://github.com/open-mmlab/mmhuman3d/discussions/48#discussion-3763206) for upcoming features.
