### ISSUE TITLE
infer one image with bug

### ISSUE THREAD

**Issue by panshaohua** [open-mmlab/mmhuman3d#9]
https://github.com/open-mmlab/mmhuman3d/blob/bd906da8cbe22948665fb3ea9d13b569119ebd88/mmhuman3d/core/visualization/visualize_smpl.py#L69
I don't know the meaning of this code.
if infer one image,  image_array's shape is [0, h, w, 3]

**Comment by JasonBoy1** [comment]
> https://github.com/open-mmlab/mmhuman3d/blob/bd906da8cbe22948665fb3ea9d13b569119ebd88/mmhuman3d/core/visualization/visualize_smpl.py#L69
> 
> 
> I don't know the meaning of this code.
> if infer one image, image_array's shape is [0, h, w, 3]

sorry, this is a mistake. In visualization, end means the end frame. If you have 10 frames, start=0,  end=9.
You could either set end = 9 or end=-1 to visualize the whole 10 frames.
So there you could change it as `(end - start + 1, 1, 1, 1)`
I will fix this in PR.

**Comment by panshaohua** [comment]
THX
