### ISSUE TITLE
Install without pickel5 and pytorch3d (on Windows)

### ISSUE THREAD

**Issue by ZhengyuLin** [open-mmlab/mmhuman3d#93]
Hi, I am trying to install the packages on Windows. I found that pickle5 can not to be installed on Windows and pytroch3d needs to be installed from source. Is it possible to install without those two packages? Rare lines of codes are depending on these. Otherwise, it works fine. Thank you.

您好，我尝试在windows下安装库和相关依赖。请问pickle5 和 pytorch3d 是否必须安装？ 它们在windows上的安装不是很方便。从requirements 中删去是否影响使用？谢谢。

**Comment by caizhongang** [comment]
Hi @ZhengyuLin , `PyTorch3D` is needed for visualization / differentiable rendering / transformations and may be difficult to do without. `pickle5` is only needed for AGORA preprocessing and can be removed.

The team is now aware of the dependency issue and we will figure out a minimum requirement list for Windows users soon.
