### ISSUE TITLE
where is "checkpoint='data/vibe_backbone.pth' "?

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmhuman3d#99]
can you release the vibe_backbone.pth file？
THX

**Comment by caizhongang** [comment]
Hi @Gzzgz , you may download vibe_backbone.pth from [here](https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmhuman3d/models/vibe/vibe_backbone.pth?versionId=CAEQKhiBgMD4yZSG9xciIGU1NDgwMDMwNGJkZjQ0MDNhNGI5MDljNmEzYzkzYjUy). 

However, we will soon update this part and a new link will be added in the documentation.

**Comment by Gzzgz** [comment]
THX。
